//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace WebApplication1
{
    #region Contextos
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    public partial class DAREntities : ObjectContext
    {
        #region Constructores
    
        /// <summary>
        /// Inicializa un nuevo objeto DAREntities usando la cadena de conexión encontrada en la sección 'DAREntities' del archivo de configuración de la aplicación.
        /// </summary>
        public DAREntities() : base("name=DAREntities", "DAREntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto DAREntities.
        /// </summary>
        public DAREntities(string connectionString) : base(connectionString, "DAREntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto DAREntities.
        /// </summary>
        public DAREntities(EntityConnection connection) : base(connection, "DAREntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Métodos parciales
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propiedades de ObjectSet
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<LOGIN> LOGIN
        {
            get
            {
                if ((_LOGIN == null))
                {
                    _LOGIN = base.CreateObjectSet<LOGIN>("LOGIN");
                }
                return _LOGIN;
            }
        }
        private ObjectSet<LOGIN> _LOGIN;

        #endregion

        #region Métodos AddTo
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet LOGIN. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToLOGIN(LOGIN lOGIN)
        {
            base.AddObject("LOGIN", lOGIN);
        }

        #endregion

    }

    #endregion

    #region Entidades
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DARModel", Name="LOGIN")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class LOGIN : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto LOGIN.
        /// </summary>
        /// <param name="id">Valor inicial de la propiedad ID.</param>
        public static LOGIN CreateLOGIN(global::System.String id)
        {
            LOGIN lOGIN = new LOGIN();
            lOGIN.ID = id;
            return lOGIN;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.String _ID;
        partial void OnIDChanging(global::System.String value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LOGIN1
        {
            get
            {
                return _LOGIN1;
            }
            set
            {
                OnLOGIN1Changing(value);
                ReportPropertyChanging("LOGIN1");
                _LOGIN1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LOGIN1");
                OnLOGIN1Changed();
            }
        }
        private global::System.String _LOGIN1;
        partial void OnLOGIN1Changing(global::System.String value);
        partial void OnLOGIN1Changed();

        #endregion

    
    }

    #endregion

    
}
