//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Plataforma_PAR.AlfonsosService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AlfonsosService.ReceptorSoap")]
    public interface ReceptorSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        Plataforma_PAR.AlfonsosService.HelloWorldResponse HelloWorld(Plataforma_PAR.AlfonsosService.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<Plataforma_PAR.AlfonsosService.HelloWorldResponse> HelloWorldAsync(Plataforma_PAR.AlfonsosService.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/solicitar", ReplyAction="*")]
        void solicitar();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/solicitar", ReplyAction="*")]
        System.Threading.Tasks.Task solicitarAsync();
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public Plataforma_PAR.AlfonsosService.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(Plataforma_PAR.AlfonsosService.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public Plataforma_PAR.AlfonsosService.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(Plataforma_PAR.AlfonsosService.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ReceptorSoapChannel : Plataforma_PAR.AlfonsosService.ReceptorSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReceptorSoapClient : System.ServiceModel.ClientBase<Plataforma_PAR.AlfonsosService.ReceptorSoap>, Plataforma_PAR.AlfonsosService.ReceptorSoap {
        
        public ReceptorSoapClient() {
        }
        
        public ReceptorSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReceptorSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReceptorSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReceptorSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Plataforma_PAR.AlfonsosService.HelloWorldResponse Plataforma_PAR.AlfonsosService.ReceptorSoap.HelloWorld(Plataforma_PAR.AlfonsosService.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            Plataforma_PAR.AlfonsosService.HelloWorldRequest inValue = new Plataforma_PAR.AlfonsosService.HelloWorldRequest();
            inValue.Body = new Plataforma_PAR.AlfonsosService.HelloWorldRequestBody();
            Plataforma_PAR.AlfonsosService.HelloWorldResponse retVal = ((Plataforma_PAR.AlfonsosService.ReceptorSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Plataforma_PAR.AlfonsosService.HelloWorldResponse> Plataforma_PAR.AlfonsosService.ReceptorSoap.HelloWorldAsync(Plataforma_PAR.AlfonsosService.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<Plataforma_PAR.AlfonsosService.HelloWorldResponse> HelloWorldAsync() {
            Plataforma_PAR.AlfonsosService.HelloWorldRequest inValue = new Plataforma_PAR.AlfonsosService.HelloWorldRequest();
            inValue.Body = new Plataforma_PAR.AlfonsosService.HelloWorldRequestBody();
            return ((Plataforma_PAR.AlfonsosService.ReceptorSoap)(this)).HelloWorldAsync(inValue);
        }
        
        public void solicitar() {
            base.Channel.solicitar();
        }
        
        public System.Threading.Tasks.Task solicitarAsync() {
            return base.Channel.solicitarAsync();
        }
    }
}
