//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Plataforma_PAR.RicardosService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://tempuri.org/z", ConfigurationName="RicardosService.atkSoap")]
    public interface atkSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/z is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/z/HelloWorld", ReplyAction="*")]
        Plataforma_PAR.RicardosService.HelloWorldResponse HelloWorld(Plataforma_PAR.RicardosService.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/z/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<Plataforma_PAR.RicardosService.HelloWorldResponse> HelloWorldAsync(Plataforma_PAR.RicardosService.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/z/solicitar", ReplyAction="*")]
        void solicitar();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/z/solicitar", ReplyAction="*")]
        System.Threading.Tasks.Task solicitarAsync();
        
        // CODEGEN: Generating message contract since element name getPortsResult from namespace http://tempuri.org/z is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/z/getPorts", ReplyAction="*")]
        Plataforma_PAR.RicardosService.getPortsResponse getPorts(Plataforma_PAR.RicardosService.getPortsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/z/getPorts", ReplyAction="*")]
        System.Threading.Tasks.Task<Plataforma_PAR.RicardosService.getPortsResponse> getPortsAsync(Plataforma_PAR.RicardosService.getPortsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/z", Order=0)]
        public Plataforma_PAR.RicardosService.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(Plataforma_PAR.RicardosService.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/z", Order=0)]
        public Plataforma_PAR.RicardosService.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(Plataforma_PAR.RicardosService.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/z")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getPortsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getPorts", Namespace="http://tempuri.org/z", Order=0)]
        public Plataforma_PAR.RicardosService.getPortsRequestBody Body;
        
        public getPortsRequest() {
        }
        
        public getPortsRequest(Plataforma_PAR.RicardosService.getPortsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getPortsRequestBody {
        
        public getPortsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getPortsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getPortsResponse", Namespace="http://tempuri.org/z", Order=0)]
        public Plataforma_PAR.RicardosService.getPortsResponseBody Body;
        
        public getPortsResponse() {
        }
        
        public getPortsResponse(Plataforma_PAR.RicardosService.getPortsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/z")]
    public partial class getPortsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getPortsResult;
        
        public getPortsResponseBody() {
        }
        
        public getPortsResponseBody(string getPortsResult) {
            this.getPortsResult = getPortsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface atkSoapChannel : Plataforma_PAR.RicardosService.atkSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class atkSoapClient : System.ServiceModel.ClientBase<Plataforma_PAR.RicardosService.atkSoap>, Plataforma_PAR.RicardosService.atkSoap {
        
        public atkSoapClient() {
        }
        
        public atkSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public atkSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public atkSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public atkSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Plataforma_PAR.RicardosService.HelloWorldResponse Plataforma_PAR.RicardosService.atkSoap.HelloWorld(Plataforma_PAR.RicardosService.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            Plataforma_PAR.RicardosService.HelloWorldRequest inValue = new Plataforma_PAR.RicardosService.HelloWorldRequest();
            inValue.Body = new Plataforma_PAR.RicardosService.HelloWorldRequestBody();
            Plataforma_PAR.RicardosService.HelloWorldResponse retVal = ((Plataforma_PAR.RicardosService.atkSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Plataforma_PAR.RicardosService.HelloWorldResponse> Plataforma_PAR.RicardosService.atkSoap.HelloWorldAsync(Plataforma_PAR.RicardosService.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<Plataforma_PAR.RicardosService.HelloWorldResponse> HelloWorldAsync() {
            Plataforma_PAR.RicardosService.HelloWorldRequest inValue = new Plataforma_PAR.RicardosService.HelloWorldRequest();
            inValue.Body = new Plataforma_PAR.RicardosService.HelloWorldRequestBody();
            return ((Plataforma_PAR.RicardosService.atkSoap)(this)).HelloWorldAsync(inValue);
        }
        
        public void solicitar() {
            base.Channel.solicitar();
        }
        
        public System.Threading.Tasks.Task solicitarAsync() {
            return base.Channel.solicitarAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Plataforma_PAR.RicardosService.getPortsResponse Plataforma_PAR.RicardosService.atkSoap.getPorts(Plataforma_PAR.RicardosService.getPortsRequest request) {
            return base.Channel.getPorts(request);
        }
        
        public string getPorts() {
            Plataforma_PAR.RicardosService.getPortsRequest inValue = new Plataforma_PAR.RicardosService.getPortsRequest();
            inValue.Body = new Plataforma_PAR.RicardosService.getPortsRequestBody();
            Plataforma_PAR.RicardosService.getPortsResponse retVal = ((Plataforma_PAR.RicardosService.atkSoap)(this)).getPorts(inValue);
            return retVal.Body.getPortsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Plataforma_PAR.RicardosService.getPortsResponse> Plataforma_PAR.RicardosService.atkSoap.getPortsAsync(Plataforma_PAR.RicardosService.getPortsRequest request) {
            return base.Channel.getPortsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Plataforma_PAR.RicardosService.getPortsResponse> getPortsAsync() {
            Plataforma_PAR.RicardosService.getPortsRequest inValue = new Plataforma_PAR.RicardosService.getPortsRequest();
            inValue.Body = new Plataforma_PAR.RicardosService.getPortsRequestBody();
            return ((Plataforma_PAR.RicardosService.atkSoap)(this)).getPortsAsync(inValue);
        }
    }
}
